### PR TITLE
Addresses several nagging issues with 1.1.3

### LINKED ISSUE #44: USING TIMESTAMP on individual DML statements within a batch fail for UPDATE or DELETE statements.
Priam should detect these clauses and not attempt to write timestamp clauses at the DML level.

Related: https://datastax-oss.atlassian.net/browse/NODEJS-86

### PR DESCRIPTION
**Pull request by scommisso**
- Resolve #44, #46
- Fix collection type encoding
- Move `helenus` to optional dependency

### CODE REVIEW

File: lib/util/batch.js [hunk 1]
```diff
@@ -121,7 +121,25 @@ function supportsCql31(version) {
...
+    });
+  } else {
+    if (containsDeleteOrUpdateRegex.test(query.context.cql)) {
+      match = true;
+    }
+  }
+  return match;
+}
+
+var containsDeleteOrUpdateRegex = /(?:update|delete)\s+[^\s,\(\)]/i;
```
Comment (JosephJNK) [inline lib/util/batch.js]: I think this could give you a false positive for certain strings a user might input. It should probably be 
/^\s*(?:update|delete)\s+[^\s,\(\)]/i

File: lib/util/batch.js [hunk 2]
```diff
@@ -129,16 +147,28 @@ function joinQueries(queries, timestamp, batchType, consistencyHierarchy, cqlVer
     , consistencyMap = null
     , hasTimestamp = false
     , hasQuery = false
-    , supportsNestedTimestamp = supportsCql31(cqlVersion)
+    , supportsNestedTimestamp = typeof cqlVersion === 'boolean' ? cqlVersion : supportsCql31(cqlVersion)
```
Comment (JosephJNK) [inline lib/util/batch.js]: I'm confused as to why this would be a boolean

File: lib/util/batch.js [hunk 3]
```diff
@@ -129,16 +147,28 @@ function joinQueries(queries, timestamp, batchType, consistencyHierarchy, cqlVer
...
     , queryConsistencyMap;
   if (!isChildBatch) {
     cql.push('BEGIN ' + getBatchTypeString(batchType) + 'BATCH');
   }
+
+  if (supportsNestedTimestamp) {
```
Comment (JosephJNK) [inline lib/util/batch.js]: I'd suggest extracting a small method here, to keep the containing method from bloating

File: lib/util/batch.js (hunk 1 above)
Comment (scommisso) [inline lib/util/batch.js]: Validated it works fine with insert statements containing 'update' or 'delete' as field names. I can also do /^\s*(?:update|delete)\s+/i

File: lib/util/batch.js (hunk 2 above)
Comment (scommisso) [inline lib/util/batch.js]: Recursive call, short circuits the version check logic from happening multiple times on nested batches.

File: lib/util/batch.js (hunk 3 above)
Comment (scommisso) [inline lib/util/batch.js]: +1, will address

File: lib/util/batch.js (hunk 1 above)
Comment (indexzero) [inline lib/util/batch.js]: This `RegExp` (as [most `RegExp` are](https://blog.liftsecurity.io/2014/11/03/regular-expression-dos-and-node.js?utm_source=nodeweekly&utm_medium=email)) is vulnerable to DOS attacks . Not a big deal since any consumer of `priam` should be sanitizing input before passing it a query.

File: lib/util/batch.js [hunk 4]
```diff
@@ -121,7 +121,25 @@ function supportsCql31(version) {
   return version.major > 3 || (version.major === 3 && version.minor >= 1);
 }
 
-var endsWithSemicolonRegex = new RegExp(/\s*;\s*$/);
+function containsDeleteOrUpdateStatement(query) {
+  var match = false;
+  if (query instanceof Batch) {
```
Comment (indexzero) [inline lib/util/batch.js]: Using `instanceof` on custom prototypes makes working with that prototype more difficult. For example I cannot write a Facade which wraps `Batch` because it isn't the exact same prototype. I wouldn't go as far as to say "`instanceof` considered harmful" (although [other folks have](http://perfectionkills.com/instanceof-considered-harmful-or-how-to-write-a-robust-isarray/)), but I generally only use it with prototypes Native to the language. 

I know `instanceof` is used in many places across `priam`, so consistency trumps the technicaly

**Comment by indexzero** [comment]
+1 with minor opinions.

File: lib/util/batch.js (hunk 4 above)
Comment (scommisso) [inline lib/util/batch.js]: I can sniff whether or not it is a batch a different way. I'll address this.

Comment (indexzero) [inline lib/util/batch.js]: Awesome. I wouldn't block this PR on that however since as I said it's done in many other places. I'll open an issue so it can be addressed separately.

Comment (indexzero) [inline lib/util/batch.js]: Issue opened: https://github.com/godaddy/node-priam/issues/46
